import type { WCBrand, WCCategory, WCProduct, WCVariation } from "./types";

/**
 * Realistic sample data used only when USE_FIXTURES=true (see lib/woocommerce/config.ts) — lets
 * this template be previewed/run before iNoTech's own WooCommerce store exists. Shapes mirror the
 * real WooCommerce REST API responses exactly, so switching back to live data later requires no
 * component changes. Category/attribute structure follows the taxonomy documented in README.md's
 * "Design system" section (cloned from pcportable.ma's real category tree as a template).
 */

export const FIXTURE_CATEGORIES: WCCategory[] = [
  { id: 1, name: "Pc Portable", slug: "pc-portable", parent: 0, description: "", display: "default", image: { id: 101, src: "/fixtures/cat-pc-portable.svg", name: "Pc Portable", alt: "Pc Portable" }, menu_order: 1, count: 3 },
  { id: 2, name: "Pc Portable Gamer", slug: "pc-portable-gamer", parent: 1, description: "", display: "default", image: null, menu_order: 1, count: 2 },
  { id: 3, name: "Pc Portable Multimedia", slug: "pc-portable-multimedia", parent: 1, description: "", display: "default", image: null, menu_order: 2, count: 1 },
  { id: 4, name: "Macbook", slug: "macbook", parent: 0, description: "", display: "default", image: { id: 102, src: "/fixtures/cat-macbook.svg", name: "Macbook", alt: "Macbook" }, menu_order: 2, count: 2 },
  { id: 5, name: "MacBook Pro", slug: "macbook-pro", parent: 4, description: "", display: "default", image: null, menu_order: 1, count: 1 },
  { id: 6, name: "MacBook Air", slug: "macbook-air", parent: 4, description: "", display: "default", image: null, menu_order: 2, count: 1 },
  { id: 7, name: "Casque VR", slug: "casque-vr", parent: 0, description: "", display: "default", image: null, menu_order: 3, count: 1 },
  { id: 8, name: "Périphérique", slug: "peripherique", parent: 0, description: "", display: "default", image: { id: 103, src: "/fixtures/cat-peripherique.svg", name: "Périphérique", alt: "Périphérique" }, menu_order: 4, count: 2 },
  { id: 9, name: "Souris", slug: "souris", parent: 8, description: "", display: "default", image: null, menu_order: 1, count: 1 },
  { id: 10, name: "Moniteur", slug: "moniteur", parent: 8, description: "", display: "default", image: null, menu_order: 2, count: 1 },
  { id: 11, name: "Accessoires", slug: "accessoires", parent: 0, description: "", display: "default", image: { id: 104, src: "/fixtures/cat-accessoires.svg", name: "Accessoires", alt: "Accessoires" }, menu_order: 5, count: 1 },
  { id: 12, name: "Cartable PC", slug: "cartable-pc", parent: 11, description: "", display: "default", image: null, menu_order: 1, count: 1 },
];

export const FIXTURE_BRANDS: WCBrand[] = [
  { id: 1, name: "HP", slug: "hp", description: "", image: { id: 201, src: "/fixtures/brand-hp.svg", name: "HP", alt: "HP" }, count: 1 },
  { id: 2, name: "Asus", slug: "asus", description: "", image: { id: 202, src: "/fixtures/brand-asus.svg", name: "Asus", alt: "Asus" }, count: 0 },
  { id: 3, name: "Lenovo", slug: "lenovo", description: "", image: { id: 203, src: "/fixtures/brand-lenovo.svg", name: "Lenovo", alt: "Lenovo" }, count: 1 },
  { id: 4, name: "Apple", slug: "apple", description: "", image: { id: 204, src: "/fixtures/brand-apple.svg", name: "Apple", alt: "Apple" }, count: 2 },
];

function cat(id: number) {
  const c = FIXTURE_CATEGORIES.find((x) => x.id === id)!;
  return { id: c.id, name: c.name, slug: c.slug };
}

function brand(id: number) {
  const b = FIXTURE_BRANDS.find((x) => x.id === id)!;
  return [{ id: b.id, name: b.name, slug: b.slug }];
}

function image(src: string, name: string): WCProduct["images"] {
  return [{ id: Math.floor(Math.random() * 100000), src, name, alt: name }];
}

const specs = (entries: Record<string, string>) =>
  Object.entries(entries).map(([name, value], index) => ({
    id: index + 1,
    name,
    visible: true,
    variation: false,
    options: [value],
  }));

export const FIXTURE_PRODUCTS: WCProduct[] = [
  {
    id: 1001,
    name: "Lenovo Legion 5 Gaming",
    slug: "lenovo-legion-5-gaming",
    permalink: "https://inotech.ma/product/lenovo-legion-5-gaming",
    type: "simple",
    status: "publish",
    sku: "LEN-LEG5-16",
    price: "12999",
    regular_price: "13999",
    sale_price: "12999",
    on_sale: true,
    featured: true,
    stock_status: "instock",
    stock_quantity: 5,
    short_description: "Laptop gaming avec carte graphique dédiée et écran 165Hz.",
    description: "<p>Le Lenovo Legion 5 combine puissance et fluidité pour le gaming et la création de contenu.</p>",
    categories: [cat(2)],
    tags: [],
    brands: brand(3),
    images: image("/fixtures/laptop-gamer-2.svg", "Lenovo Legion 5 Gaming"),
    attributes: specs({
      Processeur: "AMD Ryzen 7 7840HS",
      RAM: "16 Go",
      Stockage: "512 Go SSD",
      "Carte graphique": "NVIDIA RTX 4060",
      "Taille écran": "16″ 165Hz",
    }),
    variations: [],
    average_rating: "4.50",
    rating_count: 18,
    related_ids: [1002, 1003],
    meta_data: [],
  },
  {
    id: 1002,
    name: "MSI Cyborg 15",
    slug: "msi-cyborg-15",
    permalink: "https://inotech.ma/product/msi-cyborg-15",
    type: "simple",
    status: "publish",
    sku: "MSI-CYB-15",
    price: "10999",
    regular_price: "10999",
    sale_price: "",
    on_sale: false,
    featured: false,
    stock_status: "instock",
    stock_quantity: 8,
    short_description: "Puissance gaming nouvelle génération.",
    description: "<p>Un laptop gamer fin et léger, prêt pour les derniers titres.</p>",
    categories: [cat(2)],
    tags: [],
    images: image("/fixtures/laptop-gamer-1.svg", "MSI Cyborg 15"),
    attributes: specs({
      Processeur: "Intel Core i7-13620H",
      RAM: "16 Go",
      Stockage: "1 To SSD",
      "Carte graphique": "NVIDIA RTX 4050",
      "Taille écran": "15.6″ 144Hz",
    }),
    variations: [],
    average_rating: "4.20",
    rating_count: 9,
    related_ids: [1001, 1003],
    meta_data: [],
  },
  {
    id: 1003,
    name: "HP Pavilion 15",
    slug: "hp-pavilion-15",
    permalink: "https://inotech.ma/product/hp-pavilion-15",
    type: "simple",
    status: "publish",
    sku: "HP-PAV-15",
    price: "6499",
    regular_price: "6999",
    sale_price: "6499",
    on_sale: true,
    featured: true,
    stock_status: "instock",
    stock_quantity: 12,
    short_description: "Idéal pour la bureautique et les études.",
    description: "<p>Un laptop polyvalent pour un usage quotidien fluide.</p>",
    categories: [cat(3)],
    tags: [],
    brands: brand(1),
    images: image("/fixtures/laptop-multimedia-1.svg", "HP Pavilion 15"),
    attributes: specs({
      Processeur: "Intel Core i5-1235U",
      RAM: "8 Go",
      Stockage: "512 Go SSD",
      "Taille écran": "15.6″ Full HD",
    }),
    variations: [],
    average_rating: "4.00",
    rating_count: 24,
    related_ids: [1001, 1002],
    meta_data: [],
  },
  {
    id: 1004,
    name: "MacBook Pro 14 M3",
    slug: "macbook-pro-14-m3",
    permalink: "https://inotech.ma/product/macbook-pro-14-m3",
    type: "variable",
    status: "publish",
    sku: "APL-MBP14-M3",
    price: "21999",
    regular_price: "21999",
    sale_price: "",
    on_sale: false,
    featured: true,
    stock_status: "instock",
    stock_quantity: 4,
    short_description: "La puissance de la puce M3 dans un châssis 14 pouces.",
    description: "<p>Écran Liquid Retina XDR, autonomie toute la journée, puce Apple M3.</p>",
    categories: [cat(5)],
    tags: [],
    brands: brand(4),
    images: image("/fixtures/macbook-pro-1.svg", "MacBook Pro 14 M3"),
    attributes: [
      ...specs({ Puce: "Apple M3", RAM: "16 Go", Stockage: "512 Go SSD", "Taille écran": "14″ Liquid Retina XDR" }),
      { id: 90, name: "Couleur", visible: true, variation: true, options: ["Gris sidéral", "Argent"] },
    ],
    variations: [9001, 9002],
    average_rating: "4.90",
    rating_count: 31,
    related_ids: [1005],
    meta_data: [],
  },
  {
    id: 1005,
    name: "MacBook Air M3",
    slug: "macbook-air-m3",
    permalink: "https://inotech.ma/product/macbook-air-m3",
    type: "simple",
    status: "publish",
    sku: "APL-MBA-M3",
    price: "14999",
    regular_price: "14999",
    sale_price: "",
    on_sale: false,
    featured: false,
    stock_status: "instock",
    stock_quantity: 6,
    short_description: "Fin, léger, et silencieux — sans ventilateur.",
    description: "<p>Le MacBook Air M3 offre autonomie et performance dans un design ultra-fin.</p>",
    categories: [cat(6)],
    tags: [],
    brands: brand(4),
    images: image("/fixtures/macbook-air-1.svg", "MacBook Air M3"),
    attributes: specs({ Puce: "Apple M3", RAM: "8 Go", Stockage: "256 Go SSD", "Taille écran": "13.6″ Liquid Retina" }),
    variations: [],
    average_rating: "4.70",
    rating_count: 15,
    related_ids: [1004],
    meta_data: [],
  },
  {
    id: 1006,
    name: "Meta Quest 3",
    slug: "meta-quest-3",
    permalink: "https://inotech.ma/product/meta-quest-3",
    type: "simple",
    status: "publish",
    sku: "META-Q3-128",
    price: "5499",
    regular_price: "5499",
    sale_price: "",
    on_sale: false,
    featured: false,
    stock_status: "instock",
    stock_quantity: 7,
    short_description: "Casque de réalité mixte autonome.",
    description: "<p>Réalité mixte haute résolution, sans fil, compatible avec un large catalogue de jeux.</p>",
    categories: [cat(7)],
    tags: [],
    images: image("/fixtures/vr-headset-1.svg", "Meta Quest 3"),
    attributes: specs({ Compatibilité: "Autonome / PC VR", Résolution: "2064×2208 par œil" }),
    variations: [],
    average_rating: "4.60",
    rating_count: 11,
    related_ids: [],
    meta_data: [],
  },
  {
    id: 1007,
    name: "Logitech G Pro X Superlight",
    slug: "logitech-g-pro-x-superlight",
    permalink: "https://inotech.ma/product/logitech-g-pro-x-superlight",
    type: "simple",
    status: "publish",
    sku: "LOG-GPXS",
    price: "999",
    regular_price: "1299",
    sale_price: "999",
    on_sale: true,
    featured: true,
    stock_status: "instock",
    stock_quantity: 20,
    short_description: "Souris gaming sans fil ultra-légère.",
    description: "<p>Conçue pour l'e-sport : légèreté extrême et précision sans compromis.</p>",
    categories: [cat(9)],
    tags: [],
    images: image("/fixtures/mouse-1.svg", "Logitech G Pro X Superlight"),
    attributes: specs({ Connectivité: "Sans fil (LIGHTSPEED)", Couleur: "Noir" }),
    variations: [],
    average_rating: "4.80",
    rating_count: 42,
    related_ids: [],
    meta_data: [],
  },
  {
    id: 1008,
    name: 'AOC 27″ 165Hz',
    slug: "aoc-27-165hz",
    permalink: "https://inotech.ma/product/aoc-27-165hz",
    type: "simple",
    status: "publish",
    sku: "AOC-27-165",
    price: "2799",
    regular_price: "2799",
    sale_price: "",
    on_sale: false,
    featured: false,
    stock_status: "onbackorder",
    stock_quantity: 0,
    short_description: "Moniteur gaming 27 pouces, 165Hz, 1ms.",
    description: "<p>Un moniteur réactif pour le gaming compétitif.</p>",
    categories: [cat(10)],
    tags: [],
    images: image("/fixtures/monitor-1.svg", 'AOC 27″ 165Hz'),
    attributes: specs({ "Taille écran": "27″", Résolution: "1920×1080", "Taux de rafraîchissement": "165Hz" }),
    variations: [],
    average_rating: "4.30",
    rating_count: 7,
    related_ids: [],
    meta_data: [],
  },
  {
    id: 1009,
    name: 'Cartable PC 15.6″',
    slug: "cartable-pc-15-6",
    permalink: "https://inotech.ma/product/cartable-pc-15-6",
    type: "simple",
    status: "publish",
    sku: "BAG-156",
    price: "349",
    regular_price: "349",
    sale_price: "",
    on_sale: false,
    featured: true,
    stock_status: "instock",
    stock_quantity: 30,
    short_description: "Cartable renforcé pour PC portable jusqu'à 15.6″.",
    description: "<p>Protection et style pour transporter votre PC portable au quotidien.</p>",
    categories: [cat(12)],
    tags: [],
    images: image("/fixtures/bag-1.svg", 'Cartable PC 15.6″'),
    attributes: specs({ "Taille écran": "Jusqu'à 15.6″", Couleur: "Noir" }),
    variations: [],
    average_rating: "4.10",
    rating_count: 5,
    related_ids: [],
    meta_data: [],
  },
];

export const FIXTURE_VARIATIONS: Record<number, WCVariation[]> = {
  1004: [
    {
      id: 9001,
      sku: "APL-MBP14-M3-GRIS",
      price: "21999",
      regular_price: "21999",
      sale_price: "",
      on_sale: false,
      stock_status: "instock",
      image: { id: 301, src: "/fixtures/macbook-pro-1.svg", name: "MacBook Pro 14 M3 — Gris sidéral", alt: "MacBook Pro 14 M3 — Gris sidéral" },
      attributes: [{ id: 90, name: "Couleur", option: "Gris sidéral" }],
    },
    {
      id: 9002,
      sku: "APL-MBP14-M3-ARGENT",
      price: "21999",
      regular_price: "21999",
      sale_price: "",
      on_sale: false,
      stock_status: "instock",
      image: { id: 302, src: "/fixtures/macbook-pro-1.svg", name: "MacBook Pro 14 M3 — Argent", alt: "MacBook Pro 14 M3 — Argent" },
      attributes: [{ id: 90, name: "Couleur", option: "Argent" }],
    },
  ],
};
